- src/scripts/webpack/compiler.js
- src/scripts/webpack/config.js
- src/scripts/webpack/webpack.base.js
Closes #75
https://github.omnilab.our.buildo.io/buildo/aliniq/pull/5418
Not tested for other projects
> #75: Handle configuration whitelist from webpack config (closes #75)

- package.json
- src/scripts/webpack/webpack.base.js
Closes #81
- tested on GDSM (https://github.com/buildo/gdsm/pull/377)
> #81: webpack config should handle svg and jpg formats loading (closes #81)

- README.md
Not really sure about the configuration bit. It seems a bit obscure, is the format documented anywhere else?
> Add webpack to the readme (closes #80)

- package.json
> #98: minimist and babel-cli should be deps, not devDeps (closes #98)

- src/scripts/webpack/webpack.base.js
Closes #100
tested manually on internal project
> #100: file-loader context is not configured correctly due to a typo (closes #100)

- package.json
> #102: update typescript version (closes #102)

- src/scripts/webpack/tsconfig.json
> #104: tsconfig.json paths should be relative to user defined baseUrl (closes #104)

- bin/scriptoni.js
> #112: node v5 doesn't like `, moreArgs = []` (closes #112)

- src/scripts/metarpheus-diff/index.js
Closes #114
- tested manually on aliniq
> #114: metarpheus-diff script is broken (closes #114)

- package.json
- src/scripts/metarpheus/config.js
> #117: [metarpheus ts] optional type should be `T | undefined` (closes #117)

- bin/scriptoni.js
- src/scripts/metarpheus-diff/index.js
> #123: add metarpheus-ts-diff (closes #123)

- src/scripts/metarpheus/config.js
Closes #116
tested manually on gdsm
> #116: metarpheus-diff is still broken (closes #116)

- bin/scriptoni.js
- src/util.js
Closes #97
In the project folder:
- `mkdir build && touch build/a-file.txt`
- `ls build` list `a-file.txt`
-  `npm start`
- `ls build` list nothing ✅ 
- `ls node_modules/react-intl/node_modules` => empty ✅ 
- `ls node_modules/fixed-data-table-2/node_modules` => empty ✅ 
- `ls node_modules/revenge/node_modules` => empty ✅ 
> #97: webpack script could be nicer in the final project (closes #97)

- src/scripts/webpack/util.js
- src/scripts/webpack/webpack.base.js
- src/scripts/webpack/webpack.build.js
- src/scripts/webpack/webpack.config.js
Closes #135
- incremental build of alinity-pro with *username* and *password* (contained in `config.bundle` )in the html ✅
> #135: getHtmlPluginConfig should allow to pass an object as data for html (closes #135)

- package.json
Closes #138
Tested on GDSM web, with `virtual-module-webpack-plugin@0.3.0` and `enhanced-resolve@3.4.1`
> #138: Upgrade virtual-module-webpack-plugin (closes #138)

- src/scripts/webpack/dev-ts.js
- src/scripts/webpack/dev.js
Closes #142
- tested on alinity pro 👍 
> #142: dev server configuration should allow browser history location (closes #142)

- src/scripts/webpack/webpack.build.js
Closes #134
tested on alinity-pro:
- no build errors ✅ 
- no runtime errors ✅ 
I didn't notice any improvement in the performance, just a little reduction in the bundle size (~10kb) 😢 
> #134: Enable scope hoisting for webpack (closes #134)

- src/scripts/webpack/webpack.base.js
> #146: webpack.output.publicPath should be set to `/` (closes #146)

- package.json
> #151: Update metarpheus-io-ts version in order to kill buildo-lodash-ts (closes #151)

- package.json
- src/scripts/metarpheus/config.js
- src/scripts/metarpheus/run.js
tested manually and briefly on alinitypro
more fixes will probably be needed, but it should be in good shape now
> Upgrade metarpheus-io-ts and generate TS APIs (closes #156)

- src/scripts/metarpheus/config.js
- src/scripts/webpack/paths.js
- src/scripts/webpack/tsconfig.json
- src/scripts/webpack/util.js
- src/scripts/webpack/webpack.base.js
- src/scripts/webpack/webpack.build.js
- src/scripts/webpack/webpack.config.js
Closes #160
tested manually on a "new" template, all the imports are correct
> #160: adapt to webseed/template simplification (closes #160)

- src/scripts/webpack/tsconfig.json
> #162: tsconfig.json contains an additional , (closes #162)

- package.json
> #158: Upgrade TS to v2.6.2 (closes #158)

- package.json
> #172: upgrade metarpheus-io-ts to get newtypes support (closes #172)

- src/scripts/webpack/webpack.build.js
Closes #178
tested locally on banksealer
> #178: uglifyed build output does not work on IE11 and Chrome 38 (closes #178)

- src/scripts/webpack/build-ts.js
- src/scripts/webpack/build.js
- src/scripts/webpack/compiler.js
- src/scripts/webpack/dev-ts.js
- src/scripts/webpack/dev.js
- src/scripts/webpack/getWebpackConfig.js
- src/scripts/webpack/webpack.config.js
tested locally on LETA/admin -> 👍
> webpack: forward devServer config to webpack-dev-server (closes #186)

- src/scripts/webpack/paths.js
- src/scripts/webpack/webpack.base.js
> #189: wrong babelrc in monorepo with shared folders (closes #189)

- jest.config.js
- src/scripts/metarpheus-diff/index.js
- src/scripts/metarpheus/config.js
- src/scripts/metarpheus/index.js
- src/scripts/metarpheus/run.js
- src/scripts/webpack/tsconfig.json
- test/globalSetup.js
- test/metarpheus.test.ts
- test/template-app/fake-api-src/Account.scala
- test/template-app/metarpheus.config.test.js
- test/utils.ts
- test/webpack.test.ts
Closes #193
Added a new test for this option
> #193: metarpheus config file path should be overridable (closes #193)

- bin/scriptoni.js
> #169: can we remove the "clean react" step from every build? (closes #169)

- package.json
- test/template-app/yarn.lock
> #203: metarpheus dep should not be pinned (closes #203)

- package.json
- test/__snapshots__/webpack.test.ts.snap
- test/template-app/yarn.lock
> #205: Update to metarpheus-io-ts@0.3.0 (closes #205)

- package.json
- test/template-app/yarn.lock
> #225: upgrade TS to 3.1.x (closes #225)

- package.json
- test/globalSetup.js
> #231: TypeError: Cannot read property 'ts' of undefined (closes #231)

- package.json
- test/__snapshots__/metarpheus.test.ts.snap
- test/stylelint.test.ts
> #235: upgrade metarpheus-io-ts (closes #235)

- src/model.ts
- src/scripts/metarpheus/config.ts
> Avoid using '' as model prelude default

- src/index.ts
- src/util.ts
Closes #234
Tested locally by removing config file for `web-build`:
> #234: Scriptoni does not log errors (closes #234)

- src/model.ts
- src/scripts/webpack/config.ts
- src/scripts/webpack/webpack.build.ts
- test/__snapshots__/webpack.test.ts.snap
> #130: [webpack] no devtool in dev and prod by default (closes #130)

- .prettierrc.js
- bin/scriptoni-ts.js
- bin/scriptoni.js
- copy-files.ts
- src/index.ts
- src/model.ts
- src/scripts/prettier/.prettierrc.js
- src/scripts/prettier/getDefaultArgs.ts
- src/util.ts
- test/globalSetup.js
- test/metarpheus.test.ts
- test/runCommands.js
- test/template-app/src/components/App/App.tsx
- test/template-app/src/components/Dropdown/dropdown.scss
- test/template-app/src/components/Hello/Hello.tsx
- test/template-app/src/components/Hello/hello.scss
- test/template-app/src/components/SwitchViewDropdown/SwitchViewDropdown.tsx
- test/template-app/src/theme/main.scss
- test/template-app/src/theme/typography.scss
- test/utils.ts
- test/webpack.test.ts
- typings/metarpheus.d.ts
- typings/progress-bar-webpack-plugin.d.ts
- typings/virtual-module-webpack-plugin.d.ts
> #262: both scriptoni and VSCode ignore project's `.prettier.js` (closes #262)

- src/scripts/webpack/tsconfig.json
> #259: tsconfig.json changes proposal (closes #259)

- package.json
- test/__snapshots__/metarpheus.test.ts.snap
> #264: upgrade to metarpheus-io-ts 0.8.0 (closes #264)

- src/scripts/webpack/tsconfig.json
- src/scripts/webpack/webpack.base.ts
- test/__snapshots__/webpack.test.ts.snap
> #268: Remove magic paths (closes #268)
